In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
from bs4 import BeautifulSoup
%matplotlib inline

In [161]:
key='&columns=History.*100.PricePerUnit,History.*100.PurchaseDate'
item=requests.get('https://xivapi.com/market/ragnarok/items/10/history?key=f6797fe96fc34e0887f47ae1&language=en'+key)

In [162]:
pd.DataFrame(item.json()['History'])

     PricePerUnit  PurchaseDate
0           135.0  1.548238e+09
1           133.0  1.548238e+09
2           134.0  1.548238e+09
3           130.0  1.548237e+09
4           100.0  1.548213e+09
5            99.0  1.548213e+09
6           100.0  1.548179e+09
7            99.0  1.548179e+09
8            98.0  1.548173e+09
9           100.0  1.548163e+09
10          140.0  1.548141e+09
11          169.0  1.548093e+09
12          169.0  1.548091e+09
13          140.0  1.548091e+09
14          170.0  1.548073e+09
15          150.0  1.548030e+09
16          150.0  1.548022e+09
17          150.0  1.548022e+09
18          148.0  1.548022e+09
19          149.0  1.548022e+09
20            NaN           NaN
21            NaN           NaN
22            NaN           NaN
23            NaN           NaN
24            NaN           NaN
25            NaN           NaN
26            NaN           NaN
27            NaN           NaN
28            NaN           NaN
29            NaN           NaN
..            ...           ...
71            NaN           NaN
72            NaN           NaN
73            NaN           NaN
74            NaN           NaN
75            NaN           NaN
76            NaN           NaN
77            NaN           NaN
78            NaN           NaN
79            NaN           NaN
80            NaN           NaN
81            NaN           NaN
82            NaN           NaN
83            NaN           NaN
84            NaN           NaN
85            NaN           NaN
86            NaN           NaN
87            NaN           NaN
88            NaN           NaN
89            NaN           NaN
90            NaN           NaN
91            NaN           NaN
92            NaN           NaN
93            NaN           NaN
94            NaN           NaN
95            NaN           NaN
96            NaN           NaN
97            NaN           NaN
98            NaN           NaN
99            NaN           NaN
100           NaN           NaN

[101 rows x 2 columns]